### PR TITLE
misc: modern ruby and coveralls integration

### PR DESCRIPTION
**Pull request by ripienaar**
Also update rspec to latest and updates the rspec syntax

### CODE REVIEW

**Comment by gavin-scott** [comment]
This is still marked DNM but looks good to go to me. Thanks!

**Comment by ripienaar** [comment]
We should set up a coveralls account that isn't my personal one :) not sure of someone should set it up while logged in as the dell-asm user perhaps. Will see how it works

**Comment by ripienaar** [comment]
seems fine, i squashed and update commit message, pr message etc @gavin-scott

**Comment by gavin-scott** [comment]
Nice!

**Comment by ripienaar** [comment]
@gavin-scott i disabled the thing where coveralls comments on the PRs like above, it can be annoying but also improves visibility, think we should keep it on?

**Comment by kaushalgala** [comment]
IMHO I like the coveralls comment that indicates the coverage and a link to the coveralls report. But again, it is first time experiencing so will feel good :)  If it turns out to be annoying in future, we can turn it off. What do you say @gavin-scott ?

**Comment by ripienaar** [comment]
My personal bad habit of squashing and repeatedly
force pushing a PR while working makes it very annoying. But sure I am all for trailing the setting. Will enable later :)

**Comment by gavin-scott** [comment]
The comments seem good to me? I guess it'll become clear if they're annoying when you do lots of squash and force push? (that's my usual workflow also)

**Comment by ripienaar** [comment]
One thing i didn't mention is if test coverage decrease over a threshold the coveralls check fails just like CI fails 

So the main thing we would care about is being surfaced in another way too. 

Will enable the comments today :)

**Pull request merged**
