### PR TITLE
Forward port 8.2.1 changes to 8.3

### PR DESCRIPTION
**Pull request by gavin-scott**

### CODE REVIEW

**Comment by gavin-scott** [comment]
@asaenz can you give this forward port a quick once-over?

**Comment by gavin-scott** [comment]
@asaenz can you give this a +1 if you don't see anything glaringly wrong with this forward-port?

**Comment by asaenz** [comment]
👍

**Comment by gavin-scott** [comment]
Looks like @shaorong-zhu beat me to getting this one merged. Will merged #55 instead.

**Pull request closed without merging**
