### PR TITLE
ASM-8606 Replaced nokogiri 1.5.10 with 1.6.8 for puppet 3.8

### PR DESCRIPTION
**Pull request by arunrordell**

### CODE REVIEW

**Comment by arunrordell** [comment]
Reference PR:

https://github.com/dell-asm/asm-deployer/pull/2034
https://github.com/dell-asm/asm-automation/pull/568
https://github.com/dell-asm/razor-server/pull/133

**Comment by gavin-scott** [comment]
@ripienaar the jruby-9k failure on travis ci are very strange. It is failing to install rainbow, but if I manually run "gem install" locallly with jruby 9 that succeeds and then `bundle install` will succeed. Did you add jruby 9 to this build? Do you know if it has been successful before? The last successful build I can find only built with ruby 1.9 and jruby 1.7: https://travis-ci.org/dell-asm/dell-asm-util/builds/195230883 For some reason Travis CI didn't seem to run against the change you put in to support modern rubies: #81 

@arunrordell have a look at e.g. the ruby 1.9 travis ci build, it looks like there is a rubocop violation.

**Comment by gavin-scott** [comment]
Hmm, looks like this is the jruby 9 problem: https://github.com/sickill/rainbow/issues/48 : "Bundler 0.14 breaks (rainbow) 2.2.1 build". They say `gem update --system` fixes the issue, and I can confirm that works for me. Now to figure out how to do that as part of the travis ci build...

**Comment by ripienaar** [comment]
@gavin-scott yeh added it to get tests in for jruby we'll hopefully run soon.  Cause is https://github.com/bundler/bundler/issues/5357#issuecomment-274742137

**Comment by ripienaar** [comment]
@gavin-scott we can disable that ruby for now if its a hassle its not important

**Comment by gavin-scott** [comment]
Yeah only issue is this is a critical fix, would like to get it in now. @arunrordell can you remove jruby 9 from the `.travis.yml` in this PR? https://github.com/dell-asm/dell-asm-util/blob/e11bf5bc879691bb492973b718f73c34624d0738/.travis.yml#L6 That should allow it to pass.

**Comment by gavin-scott** [comment]
Reporting conflicts now, I can't merge.

**Pull request merged**
